apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-helm
spec:
  destination:
    namespace: user1-bgdh
    server: 'https://kubernetes.default.svc'
  source:
    path: helm
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: bgd
    targetRevision: master
    helm:
      valueFiles:
      - values1.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true