---
zonda: null
appName: user1
appTargetEnv: bgdh
clusterEnv: qa
IMAGE_VERSION: 1.0.0
appCluster: apps.cluster-fhz8c.fhz8c.sandbox1667.opentlc.com
deployments:
  - name: ext
    healthcheck: true
    envsize: extraflexible
    routeannotation: |
      haproxy.router.openshift.io/timeout: 300s
    replicas: 1