{{- if .Values.externalsecrets }}
{{- range $es :=.Values.externalsecrets }}
{{ $namespace := printf "%s-%s" $.Values.appName $.Values.appTargetEnv }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ default .awsSecretName .desiredsecretname }}
  namespace: {{ $.Values.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .secretStoreRefName }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ default .awsSecretName .desiredsecretname }}
  data:
    - secretKey: secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .awsSecretName }}
      
  refreshInterval: 1h
{{ end }}
{{ end }}
