{{ $namespace := printf "%s-%s" $.Values.appName $.Values.appTargetEnv }}
---
## Zonda Deployment Config
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
