---
# Source: mychart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: lucky-turkey-secret
type: Opaque
data:
  some-file.txt: |-
        {{ .Files.Get "properties.properties" | b64enc  }}
  some-file1.txt: |-
        {{ .Files.Get "properties1.properties" | b64enc  }}
  some-file2.txt: |-
        {{ .Files.Get "properties2.properties" | b64enc  }}