{{- if .Values.secrets }}
{{- range $es :=.Values.secrets }}
{{ $fullName := printf "%s-%s" $.Values.appName .name }}
{{ $namespace := printf "%s-%s" $.Values.appName $.Values.appTargetEnv }}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $es.name }}
  namespace: "{{ $namespace }}"
  labels:
    app.kubernetes.io/instance: {{ $.Values.appName }}-{{ $.Values.appTargetEnv }}
spec:
  refreshInterval: {{ default "1h" $es.customRefreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  {{- if eq (.namekey) ".dockerconfigjson" }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ $es.namekey | toString }}"
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $es.awsKey }}
    secretKey: {{ $es.namekey }}
  {{- else }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $es.awsKey }}
      property: {{ $es.property }}
    secretKey: {{ $es.namekey }}
  {{ end }}
{{ end }}
{{ end }}
