---
# Source: mychart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test1
type: Opaque
data:
  properties.properties: |-
        {{ .Files.Get "properties.properties" | b64enc  }}
  properties1.properties: |-
        {{ .Files.Get "properties1.properties" | b64enc  }}
  properties2.properties: |-
        {{ .Files.Get "properties2.properties" | b64enc  }}
  some-file3.xml: |-
        {{ .Files.Get "random.xml" | b64enc  }}
---
# Source: mychart/templates/secret.yaml
apiVersion: v1
kind: test2
metadata:
  name: lucky-turkey-secret
type: Opaque
data:
  newkeystore.jks: |-
        {{ .Files.Get "newkeystore.jks" | b64enc  }}